version: "3"
services:
  flask_app:
    container_name: flask_app
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - TESTING=true
    ports:
      - "5000:5000"
    volumes:
      - .:/flask_app
    depends_on:
      - mysql
  
  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql

volumes:
  mydatabase:
